### ISSUE TITLE
GreedyPack Failure to Pack

### ISSUE THREAD

**Issue by martensievers** [shopgun/pack-animal#46]
Error: greedyPack failure to pack, please open an issue at https://github.com/shopgun/pack-animal/issues and include this data:
eyJwb2x5Z29ucyI6W1t7IngiOjAsInkiOjB9LHsieCI6MTYwOSwieSI6MH0seyJ4IjoxNjA5LCJ5IjoyNjB9LHsieCI6MCwieSI6MjYwfSx7IngiOjAsInkiOjB9XSxbeyJ4IjowLCJ5IjowfSx7IngiOjE4OTIsInkiOjB9LHsieCI6MTg5MiwieSI6Mjc5M30seyJ4IjowLCJ5IjoyNzkzfSx7IngiOjAsInkiOjB9XV0sInJlY3RhbmdsZUhlaWdodCI6OTEsInJlY3RhbmdsZVdpZHRoIjoxNDR9
    at greedyPack (/opt/bumblebee/node_modules/pack-animal/dist/pack-animal.umd.js:1260:19)
    at packAnimal (/opt/bumblebee/node_modules/pack-animal/dist/pack-animal.umd.js:1870:29)
    at renderImageViews (/opt/bumblebee/publication_core/offer/templates/images.js:76:29)
    at Object.module.exports [as images] (/opt/bumblebee/publication_core/offer/templates/images.js:21:22)
    at Object.render (/opt/bumblebee/publication_modules/fleggaard/templates/offer_cell/index.js:257:45)
    at blocks.forEach (/opt/bumblebee/publication_modules/fleggaard/templates/offer_cell/index.js:377:19)
    at Map.forEach (<anonymous>)
    at module.exports (/opt/bumblebee/publication_modules/fleggaard/templates/offer_cell/index.js:375:12)
    at child_views.grid.cells.map (/opt/bumblebee/publication_modules/fleggaard/templates/offers-grid.js:31:20)
    at Array.map (<anonymous>)
    at module.exports (/opt/bumblebee/publication_modules/fleggaard/templates/offers-grid.js:30:33)
    at Object.renderSection (/opt/bumblebee/publication_core/incito-builder.js:277:46)
    at Object.build (/opt/bumblebee/publication_core/incito-builder.js:79:59)
    at <anonymous>

**Comment by martensievers** [comment]
I just saw that we have a bunch of these errors in the log again. Can you help me look into this @klarstrup?

greedyPack failure to pack, please open an issue at https://github.com/shopgun/pack-animal/issues and include this data:
eyJwb2x5Z29ucyI6W1t7IngiOjAsInkiOjB9LHsieCI6MTYwOSwieSI6MH0seyJ4IjoxNjA5LCJ5IjoyNjB9LHsieCI6MCwieSI6MjYwfSx7IngiOjAsInkiOjB9XSxbeyJ4IjowLCJ5IjowfSx7IngiOjIxOTUsInkiOjB9LHsieCI6MjE5NSwieSI6MTgzNH0seyJ4IjowLCJ5IjoxODM0fSx7IngiOjAsInkiOjB9XV0sInJlY3RhbmdsZUhlaWdodCI6MTEzLCJyZWN0YW5nbGVXaWR0aCI6MTE0LjY2NjY2NjY2NjY2NjY2fQ==
